export const ERROR = 'app/error'
export const APP_TURN_ON_LOADING = 'app/loading/on'
export const APP_TURN_OFF_LOADING = 'app/loading/off'
export const OPEN_TOAST = 'app/toast/open'
export const CLOSE_TOAST = 'app/toast/close'

export const OPEN_DRAWER = 'drawer/openDrawer'
export const CLOSE_DRAWER = 'drawer/closeDrawer'

export const CHANGE_PAGE = 'posts/changePage'
export const CHANGE_ROW_PER_PAGE = 'posts/changeRowPerPage'
export const SET_ORDER = 'posts/setOrder'
export const SET_ORDER_COLUMN = 'posts/setOrderColumn'
export const SET_SELECTED_POST = 'posts/setSelectedPost'
export const SELECT_ALL_POSTS = 'posts/selectAllPosts'
export const CLEAR_SELECTED = 'posts/clearSelected'
export const FETCH_POSTS = 'posts/fetchPosts'

export const FETCH_POST = 'post/fetchPost'
export const EDIT_POST_TITLE = 'post/editPostTitle'
export const EDIT_POST_SLUG = 'post/editPostSlug'
export const EDIT_POST_BRIEF = 'post/editPostBrief'
export const EDIT_POST_AUTHOR = 'post/editPostAuthor'
export const EDIT_POST_TIME = 'post/editPostTime'
export const EDIT_POST_TAGS = 'post/editPostTags'
export const EDIT_POST_CONTENT = 'post/editPostContent'
export const SAVE_EDITED_CONTENT = 'post/saveEditedContent'
export const CREATE_NEW_POST = 'post/createNewPost'
export const INIT_POST = 'post/initPost'
