name: danger

on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: install yarn
        run: npm install -g yarn
      - name: yarn install, build, and test
        run: yarn install  --frozen-lockfile
      - name: Danger JS Action
        uses: danger/danger-js@9.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_GIT_ACTION }}
